import Config

# Configure your database
config :babel_music, BabelMusic.Repo,
  username: "postgres",
  password: "postgres",
  hostname: "localhost",
  database: "babel_music_dev",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we use it
# with esbuild to bundle .js and .css sources.
config :babel_music, BabelMusicWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}, port: 4000],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "OoVIsS520pj/ATQD5JO8qb+bjIyxqRgkFaa+KsMT8YcXdqJ7BrrPS4MAugmOeMwk",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:default, ~w(--sourcemap=inline --watch)]},
    tailwind: [
      "./node_modules/.bin/tailwindcss",
      "-i",
      "css/app.css",
      "-o",
      "../priv/static/assets/app.css",
      "-c",
      "tailwind.config.js",
      "--watch",
      cd: Path.expand("../assets", __DIR__)
    ]
  ]

config :spotify_ex,
  callback_url: "https://geometer-oliver.ngrok.io/users/spotify/callback"

# SSL Suppor
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Watch static and templates for browser reloading.
config :babel_music, BabelMusicWeb.Endpoint,
  live_reload: [
    patterns: [
      ~r"priv/static/.*(js|css|png|jpeg|jpg|gif|svg)$",
      ~r"priv/gettext/.*(po)$",
      ~r"lib/babel_music_web/(live|views)/.*(ex)$",
      ~r"lib/babel_music_web/templates/.*(eex)$"
    ]
  ]

# Enable dev routes for dashboard and mailbox
config :babel_music, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :console, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false
